例外というのはヌルポとかだけではなくて、自分でiの値が１０以上だったら例外だと決めることができる

【try-catch-finallyについて】
try
try内で例外が起こった場合、catchに処理が移る。
例外が起こった瞬間にtry内の処理が終わってしまうので、１行目で例外が起きれば２行目は処理されない。

catch　型がエラー　引数がe（eではなくてもいいけど）
型はtryで起こりうるエラーの型にしておく必要がある。

finally
書かなくても別にいい。書いたら例外が起きても怒らなくても必ず実行される。


【throwsについて】
try
ここで例外が起こりうる処理に引数を渡してメソッドを作る

throws
引数を渡されたメソッドを作成。
例外が起きるかもしれない処理をここで書く

catch
throwsで例外が起こった場合、catchで受け取り、例外が起こった場合の処理をする

【throwについて】
例外を任意のタイミングで起こすことができる
任意のタイミングで例外が起きれば、catchで受け取った処理をする。
